import type { IJob, IJobRun } from './types';
import type { IChangeHistoryItem } from '@/components/ui';

export const generateRunLogs = (jobId: string, status: 'SUCCESS' | 'FAILED'): NonNullable<IJobRun['logs']> => {
  const logs: NonNullable<IJobRun['logs']> = [
    { timestamp: new Date(Date.now() - 60000).toISOString(), level: 'INFO' as const, step: 'Initialization', message: `[${jobId}] Job started, initializing...` },
    { timestamp: new Date(Date.now() - 50000).toISOString(), level: 'INFO' as const, step: 'Connection', message: 'Connecting to data source...' },
    { timestamp: new Date(Date.now() - 40000).toISOString(), level: 'INFO' as const, step: 'Validation', message: 'Validating data schema...' },
    { timestamp: new Date(Date.now() - 30000).toISOString(), level: 'INFO' as const, step: 'Processing', message: 'Processing 5000 records...' },
  ];

  if (status === 'FAILED') {
    logs.push({ timestamp: new Date(Date.now() - 20000).toISOString(), level: 'WARN' as const, step: 'Processing', message: 'Warning: 10 records skipped due to validation error' });
    logs.push({ timestamp: new Date(Date.now() - 10000).toISOString(), level: 'ERROR' as const, step: 'Processing', message: 'Error: Database connection timeout after 30s' });
  } else {
    logs.push({ timestamp: new Date(Date.now() - 20000).toISOString(), level: 'INFO' as const, step: 'Completion', message: 'All 5000 records processed successfully' });
    logs.push({ timestamp: new Date(Date.now() - 10000).toISOString(), level: 'INFO' as const, step: 'Cleanup', message: 'Closing database connections...' });
    logs.push({ timestamp: new Date(Date.now() - 5000).toISOString(), level: 'INFO' as const, step: 'Summary', message: 'Job completed successfully. Duration: 1m 55s' });
  }

  return logs;
};

export const mockJobs: IJob[] = [
  {
    id: 'job-001',
    code: 'SYNC_CUSTOMER_DB',
    name: 'Đồng bộ dữ liệu khách hàng',
    description: 'Đồng bộ dữ liệu khách hàng từ hệ thống CRM vào data warehouse hàng ngày',
    category: 'DATA_SYNC',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 1,
    owner: 'admin_01',
    tags: ['khách-hàng', 'hàng-ngày'],
    schedule: {
      type: 'CRON',
      expression: '0 2 * * *',
      lastRunTime: '2026-05-20 02:15:32',
      nextRunTime: '2026-05-21 02:00:00',
    },
    timeout: 3600000,
    retryPolicy: { maxRetries: 3, delayMs: 5000, backoffMultiplier: 2 },
    dataSource: 'CRM_System',
    dataDestination: 'DataWarehouse_DW',
    successCount: 45,
    failureCount: 2,
    successRate: 95.7,
    avgDuration: 1200000,
    version: '2.1.0',
    createdBy: 'admin_01',
    createdAt: '2026-01-15 10:30:00',
    updatedBy: 'admin_01',
    updatedAt: '2026-05-10 14:20:00',
    dependsOn: [],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [],
    notificationMatrix: {
      onStart: { sms: false, push: false, email: true },
      onSuccess: { sms: false, push: false, email: true },
      onSlaBreach: { sms: false, push: false, email: true },
      onFailure: { sms: true, push: true, email: true, customRecipients: ['alert_group@cic.org.vn'] },
      onRetry: { sms: false, push: true, email: false },
    },
  },
  {
    id: 'job-002',
    code: 'DAILY_REPORT_GEN',
    name: 'Sinh báo cáo hàng ngày',
    description: 'Sinh báo cáo hiệu suất bán hàng hàng ngày lúc 8 sáng',
    category: 'REPORT',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 2,
    owner: 'manager_01',
    tags: ['báo-cáo', 'hàng-ngày'],
    schedule: {
      type: 'CRON',
      expression: '0 8 * * *',
      lastRunTime: '2026-05-20 08:12:45',
      nextRunTime: '2026-05-21 08:00:00',
    },
    timeout: 1800000,
    retryPolicy: { maxRetries: 2, delayMs: 3000, backoffMultiplier: 1.5 },
    successCount: 50,
    failureCount: 0,
    successRate: 100,
    avgDuration: 300000,
    version: '1.5.0',
    createdBy: 'admin_01',
    createdAt: '2026-02-01 09:00:00',
    updatedBy: 'manager_01',
    updatedAt: '2026-05-18 11:30:00',
    dependsOn: ['job-001'],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [{ jobId: 'job-001', conditionType: 'SUCCESS' }],
  },
  {
    id: 'job-003',
    code: 'CLEANUP_TEMP_DATA',
    name: 'Xóa dữ liệu tạm',
    description: 'Dọn dẹp dữ liệu tạm thời và log cũ hơn 30 ngày',
    category: 'CLEANUP',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 3,
    owner: 'admin_01',
    tags: ['dọn-dẹp', 'hàng-tuần'],
    schedule: {
      type: 'CRON',
      expression: '0 3 * * 0',
      lastRunTime: '2026-05-18 03:45:12',
      nextRunTime: '2026-05-25 03:00:00',
    },
    timeout: 600000,
    retryPolicy: { maxRetries: 1, delayMs: 2000, backoffMultiplier: 1 },
    successCount: 10,
    failureCount: 1,
    successRate: 90.9,
    avgDuration: 180000,
    version: '1.0.0',
    createdBy: 'admin_01',
    createdAt: '2026-01-20 08:00:00',
    updatedBy: 'admin_01',
    updatedAt: '2026-04-15 10:00:00',
    dependsOn: [],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [],
    notificationMatrix: {
      onStart: { sms: false, push: false, email: true },
      onSuccess: { sms: false, push: false, email: true },
      onSlaBreach: { sms: false, push: false, email: true },
      onFailure: { sms: true, push: true, email: true, customRecipients: ['alert_group@cic.org.vn'] },
      onRetry: { sms: false, push: true, email: false },
    },
  },
  {
    id: 'job-004',
    code: 'VALIDATE_TXN_DATA',
    name: 'Kiểm tra dữ liệu giao dịch',
    description: 'Kiểm tra và xác thực dữ liệu giao dịch hàng giờ',
    category: 'VALIDATION',
    status: 'ACTIVE',
    runStatus: 'RUNNING',
    priority: 1,
    owner: 'admin_01',
    tags: ['giao-dịch', 'hàng-giờ'],
    schedule: {
      type: 'CRON',
      expression: '0 * * * *',
      lastRunTime: '2026-05-20 19:15:00',
      nextRunTime: '2026-05-20 20:00:00',
    },
    timeout: 1200000,
    retryPolicy: { maxRetries: 3, delayMs: 5000, backoffMultiplier: 2 },
    successCount: 480,
    failureCount: 5,
    successRate: 98.97,
    avgDuration: 240000,
    version: '3.2.1',
    createdBy: 'admin_01',
    createdAt: '2026-01-10 12:00:00',
    updatedBy: 'admin_01',
    updatedAt: '2026-05-15 09:30:00',
    dependsOn: [],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [],
    notificationMatrix: {
      onStart: { sms: false, push: false, email: true },
      onSuccess: { sms: false, push: false, email: true },
      onSlaBreach: { sms: false, push: false, email: true },
      onFailure: { sms: true, push: true, email: true, customRecipients: ['alert_group@cic.org.vn'] },
      onRetry: { sms: false, push: true, email: false },
    },
  },
  {
    id: 'job-005',
    code: 'BATCH_PROCESS_SETTLEMENT',
    name: 'Xử lý thanh toán hàng loạt',
    description: 'Xử lý và thanh toán hàng loạt cuối ngày',
    category: 'BATCH',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 1,
    owner: 'admin_01',
    tags: ['thanh-toán', 'cuối-ngày'],
    schedule: {
      type: 'CRON',
      expression: '0 23 * * *',
      lastRunTime: '2026-05-19 23:45:33',
      nextRunTime: '2026-05-20 23:00:00',
    },
    timeout: 7200000,
    retryPolicy: { maxRetries: 5, delayMs: 10000, backoffMultiplier: 2 },
    dataSource: 'TXN_Queue',
    dataDestination: 'Settlement_System',
    successCount: 30,
    failureCount: 0,
    successRate: 100,
    avgDuration: 1800000,
    version: '1.8.0',
    createdBy: 'admin_01',
    createdAt: '2026-01-05 14:00:00',
    updatedBy: 'admin_01',
    updatedAt: '2026-05-12 16:20:00',
    dependsOn: ['job-004'],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [{ jobId: 'job-004', conditionType: 'SUCCESS' }],
  },
  {
    id: 'job-006',
    code: 'SYNC_PRODUCT_CATALOG',
    name: 'Đồng bộ danh mục sản phẩm',
    description: 'Đồng bộ danh mục sản phẩm từ hệ thống quản lý sản phẩm',
    category: 'DATA_SYNC',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 2,
    owner: 'manager_02',
    tags: ['sản-phẩm', 'đồng-bộ'],
    schedule: {
      type: 'CRON',
      expression: '0 4 * * *',
      lastRunTime: '2026-05-20 04:20:15',
      nextRunTime: '2026-05-21 04:00:00',
    },
    timeout: 900000,
    retryPolicy: { maxRetries: 2, delayMs: 3000, backoffMultiplier: 1.5 },
    dataSource: 'ProductMgmt_DB',
    dataDestination: 'CatalogService',
    successCount: 35,
    failureCount: 3,
    successRate: 92.1,
    avgDuration: 450000,
    version: '1.2.0',
    createdBy: 'admin_01',
    createdAt: '2026-02-10 11:00:00',
    updatedBy: 'manager_02',
    updatedAt: '2026-05-17 13:45:00',
    dependsOn: [],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [],
    notificationMatrix: {
      onStart: { sms: false, push: false, email: true },
      onSuccess: { sms: false, push: false, email: true },
      onSlaBreach: { sms: false, push: false, email: true },
      onFailure: { sms: true, push: true, email: true, customRecipients: ['alert_group@cic.org.vn'] },
      onRetry: { sms: false, push: true, email: false },
    },
  },
  {
    id: 'job-007',
    code: 'CHECK_SYSTEM_HEALTH',
    name: 'Kiểm tra sức khỏe hệ thống',
    description: 'Kiểm tra lỗi và cảnh báo sức khỏe hệ thống mỗi 30 phút',
    category: 'VALIDATION',
    status: 'ACTIVE',
    runStatus: 'RUNNING',
    priority: 2,
    owner: 'admin_01',
    tags: ['hệ-thống', 'giám-sát'],
    schedule: {
      type: 'CRON',
      expression: '*/30 * * * *',
      lastRunTime: '2026-05-20 19:30:05',
      nextRunTime: '2026-05-20 20:00:00',
    },
    timeout: 300000,
    retryPolicy: { maxRetries: 1, delayMs: 1000, backoffMultiplier: 1 },
    successCount: 1000,
    failureCount: 5,
    successRate: 99.5,
    avgDuration: 60000,
    version: '2.0.0',
    createdBy: 'admin_01',
    createdAt: '2026-01-25 10:00:00',
    updatedBy: 'admin_01',
    updatedAt: '2026-05-19 08:00:00',
    dependsOn: [],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [],
    notificationMatrix: {
      onStart: { sms: false, push: false, email: true },
      onSuccess: { sms: false, push: false, email: true },
      onSlaBreach: { sms: false, push: false, email: true },
      onFailure: { sms: true, push: true, email: true, customRecipients: ['alert_group@cic.org.vn'] },
      onRetry: { sms: false, push: true, email: false },
    },
  },
  {
    id: 'job-008',
    code: 'BACKUP_DATABASE',
    name: 'Sao lưu cơ sở dữ liệu',
    description: 'Sao lưu toàn bộ cơ sở dữ liệu mỗi tuần',
    category: 'BATCH',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 1,
    owner: 'admin_01',
    tags: ['sao-lưu', 'hàng-tuần'],
    schedule: {
      type: 'CRON',
      expression: '0 1 * * 1',
      lastRunTime: '2026-05-19 01:30:45',
      nextRunTime: '2026-05-26 01:00:00',
    },
    timeout: 5400000,
    retryPolicy: { maxRetries: 3, delayMs: 30000, backoffMultiplier: 2 },
    dataDestination: 'Backup_Storage',
    successCount: 22,
    failureCount: 1,
    successRate: 95.65,
    avgDuration: 2400000,
    version: '1.5.0',
    createdBy: 'admin_01',
    createdAt: '2026-01-12 09:00:00',
    updatedBy: 'admin_01',
    updatedAt: '2026-05-10 12:00:00',
    dependsOn: [],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [],
    notificationMatrix: {
      onStart: { sms: false, push: false, email: true },
      onSuccess: { sms: false, push: false, email: true },
      onSlaBreach: { sms: false, push: false, email: true },
      onFailure: { sms: true, push: true, email: true, customRecipients: ['alert_group@cic.org.vn'] },
      onRetry: { sms: false, push: true, email: false },
    },
  },
  {
    id: 'job-009',
    code: 'EXPORT_MONTHLY_STATEMENT',
    name: 'Xuất báo cáo hàng tháng',
    description: 'Xuất báo cáo tài chính hàng tháng vào ngày 1 của tháng',
    category: 'REPORT',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 2,
    owner: 'manager_01',
    tags: ['báo-cáo', 'hàng-tháng'],
    schedule: {
      type: 'CRON',
      expression: '0 9 1 * *',
      lastRunTime: '2026-05-01 09:15:22',
      nextRunTime: '2026-06-01 09:00:00',
    },
    timeout: 1800000,
    retryPolicy: { maxRetries: 2, delayMs: 5000, backoffMultiplier: 2 },
    dataDestination: 'Report_Storage',
    successCount: 5,
    failureCount: 0,
    successRate: 100,
    avgDuration: 600000,
    version: '1.1.0',
    createdBy: 'admin_01',
    createdAt: '2026-03-01 10:00:00',
    updatedBy: 'manager_01',
    updatedAt: '2026-05-01 14:00:00',
    dependsOn: ['job-002'],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [{ jobId: 'job-002', conditionType: 'SUCCESS' }],
  },
  {
    id: 'job-010',
    code: 'UPDATE_EXCHANGE_RATES',
    name: 'Cập nhật tỷ giá ngoại tệ',
    description: 'Cập nhật tỷ giá ngoại tệ từ API external mỗi 4 giờ',
    category: 'DATA_SYNC',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 2,
    owner: 'manager_03',
    tags: ['tỷ-giá', '4-giờ'],
    schedule: {
      type: 'CRON',
      expression: '0 */4 * * *',
      lastRunTime: '2026-05-20 16:05:33',
      nextRunTime: '2026-05-20 20:00:00',
    },
    timeout: 600000,
    retryPolicy: { maxRetries: 3, delayMs: 2000, backoffMultiplier: 1.5 },
    dataSource: 'ExchangeRate_API',
    dataDestination: 'CurrencyCache',
    successCount: 150,
    failureCount: 2,
    successRate: 98.67,
    avgDuration: 120000,
    version: '1.3.0',
    createdBy: 'admin_01',
    createdAt: '2026-02-20 08:00:00',
    updatedBy: 'manager_03',
    updatedAt: '2026-05-15 10:30:00',
    dependsOn: [],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [],
    notificationMatrix: {
      onStart: { sms: false, push: false, email: true },
      onSuccess: { sms: false, push: false, email: true },
      onSlaBreach: { sms: false, push: false, email: true },
      onFailure: { sms: true, push: true, email: true, customRecipients: ['alert_group@cic.org.vn'] },
      onRetry: { sms: false, push: true, email: false },
    },
  },
  {
    id: 'job-011',
    code: 'CLEAR_AUDIT_LOGS',
    name: 'Xóa log audit cũ',
    description: 'Xóa log audit cũ hơn 90 ngày hàng tháng',
    category: 'CLEANUP',
    status: 'INACTIVE',
    runStatus: 'IDLE',
    priority: 3,
    owner: 'admin_01',
    tags: ['audit', 'dọn-dẹp'],
    schedule: {
      type: 'CRON',
      expression: '0 2 1 * *',
      lastRunTime: '2026-05-01 02:30:15',
      nextRunTime: '2026-06-01 02:00:00',
    },
    timeout: 1200000,
    retryPolicy: { maxRetries: 1, delayMs: 3000, backoffMultiplier: 1 },
    successCount: 5,
    failureCount: 0,
    successRate: 100,
    avgDuration: 300000,
    version: '1.0.0',
    createdBy: 'admin_01',
    createdAt: '2026-03-15 11:00:00',
    updatedBy: 'admin_01',
    updatedAt: '2026-05-01 09:00:00',
    dependsOn: [],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [],
    notificationMatrix: {
      onStart: { sms: false, push: false, email: true },
      onSuccess: { sms: false, push: false, email: true },
      onSlaBreach: { sms: false, push: false, email: true },
      onFailure: { sms: true, push: true, email: true, customRecipients: ['alert_group@cic.org.vn'] },
      onRetry: { sms: false, push: true, email: false },
    },
  },
  {
    id: 'job-012',
    code: 'SYNC_USER_PERMISSIONS',
    name: 'Đồng bộ quyền người dùng',
    description: 'Đồng bộ quyền người dùng từ LDAP mỗi sáng',
    category: 'DATA_SYNC',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 2,
    owner: 'admin_01',
    tags: ['người-dùng', 'quyền-hạn'],
    schedule: {
      type: 'CRON',
      expression: '0 6 * * *',
      lastRunTime: '2026-05-20 06:12:45',
      nextRunTime: '2026-05-21 06:00:00',
    },
    timeout: 900000,
    retryPolicy: { maxRetries: 2, delayMs: 5000, backoffMultiplier: 2 },
    dataSource: 'LDAP_Server',
    dataDestination: 'PermissionCache',
    successCount: 40,
    failureCount: 2,
    successRate: 95.24,
    avgDuration: 180000,
    version: '1.4.0',
    createdBy: 'admin_01',
    createdAt: '2026-02-05 10:00:00',
    updatedBy: 'admin_01',
    updatedAt: '2026-05-12 14:20:00',
    dependsOn: [],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [],
    notificationMatrix: {
      onStart: { sms: false, push: false, email: true },
      onSuccess: { sms: false, push: false, email: true },
      onSlaBreach: { sms: false, push: false, email: true },
      onFailure: { sms: true, push: true, email: true, customRecipients: ['alert_group@cic.org.vn'] },
      onRetry: { sms: false, push: true, email: false },
    },
  },
  {
    id: 'job-013',
    code: 'RECONCILE_ACCOUNTS',
    name: 'Đối soát tài khoản',
    description: 'Đối soát và kiểm tra tính chính xác tài khoản hàng ngày',
    category: 'VALIDATION',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 1,
    owner: 'manager_04',
    tags: ['đối-soát', 'hàng-ngày'],
    schedule: {
      type: 'CRON',
      expression: '0 5 * * *',
      lastRunTime: '2026-05-20 05:45:12',
      nextRunTime: '2026-05-21 05:00:00',
    },
    timeout: 2400000,
    retryPolicy: { maxRetries: 3, delayMs: 10000, backoffMultiplier: 2 },
    successCount: 45,
    failureCount: 1,
    successRate: 97.83,
    avgDuration: 900000,
    version: '2.0.0',
    createdBy: 'admin_01',
    createdAt: '2026-01-18 12:00:00',
    updatedBy: 'manager_04',
    updatedAt: '2026-05-18 11:00:00',
    dependsOn: ['job-005'],
  },
  {
    id: 'job-014',
    code: 'GENERATE_COMPLIANCE_REPORT',
    name: 'Sinh báo cáo tuân thủ',
    description: 'Sinh báo cáo tuân thủ pháp lý hàng tuần',
    category: 'REPORT',
    status: 'ACTIVE',
    runStatus: 'IDLE',
    priority: 1,
    owner: 'manager_01',
    tags: ['compliance', 'hàng-tuần'],
    schedule: {
      type: 'CRON',
      expression: '0 7 * * 1',
      lastRunTime: '2026-05-19 07:30:20',
      nextRunTime: '2026-05-26 07:00:00',
    },
    timeout: 3600000,
    retryPolicy: { maxRetries: 2, delayMs: 5000, backoffMultiplier: 2 },
    dataDestination: 'ComplianceArchive',
    successCount: 10,
    failureCount: 1,
    successRate: 90.91,
    avgDuration: 1200000,
    version: '1.2.0',
    createdBy: 'admin_01',
    createdAt: '2026-02-28 09:00:00',
    updatedBy: 'manager_01',
    updatedAt: '2026-05-19 10:15:00',
    dependsOn: ['job-002'],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [{ jobId: 'job-002', conditionType: 'SUCCESS' }],
  },
  {
    id: 'job-015',
    code: 'ARCHIVE_OLD_TRANSACTIONS',
    name: 'Lưu trữ giao dịch cũ',
    description: 'Lưu trữ các giao dịch cũ hơn 1 năm vào kho lưu trữ',
    category: 'BATCH',
    status: 'ARCHIVED',
    runStatus: 'IDLE',
    priority: 3,
    owner: 'admin_01',
    tags: ['lưu-trữ', 'quá-cũ'],
    schedule: {
      type: 'CRON',
      expression: '0 0 1 * *',
      lastRunTime: '2026-05-01 00:45:33',
      nextRunTime: '2026-06-01 00:00:00',
    },
    timeout: 7200000,
    retryPolicy: { maxRetries: 1, delayMs: 5000, backoffMultiplier: 1 },
    dataSource: 'TransactionDB',
    dataDestination: 'ArchiveStorage',
    successCount: 3,
    failureCount: 1,
    successRate: 75.0,
    avgDuration: 1800000,
    version: '1.0.0',
    createdBy: 'admin_01',
    createdAt: '2026-04-15 13:00:00',
    updatedBy: 'admin_01',
    updatedAt: '2026-05-01 08:00:00',
    dependsOn: [],
    slaTimeout: 1800,
    retentionSuccess: 7,
    retentionError: 30,
    dependencies: [],
    notificationMatrix: {
      onStart: { sms: false, push: false, email: true },
      onSuccess: { sms: false, push: false, email: true },
      onSlaBreach: { sms: false, push: false, email: true },
      onFailure: { sms: true, push: true, email: true, customRecipients: ['alert_group@cic.org.vn'] },
      onRetry: { sms: false, push: true, email: false },
    },
  },
];

export const mockJobRuns: IJobRun[] = [
  {
    id: 'run-001',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-20 02:15:00',
    endTime: '2026-05-20 02:35:20',
    duration: 1220000,
    retryCount: 0,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 5000,
    recordsFailed: 0,
  },
  {
    id: 'run-002',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-19 02:15:00',
    endTime: '2026-05-19 02:34:15',
    duration: 1155000,
    retryCount: 0,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 4950,
    recordsFailed: 5,
  },
  {
    id: 'run-003',
    jobId: 'job-001',
    status: 'FAILED',
    startTime: '2026-05-18 02:15:00',
    endTime: '2026-05-18 02:28:45',
    duration: 825000,
    retryCount: 3,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 3200,
    recordsFailed: 45,
    errorMessage: 'Database connection timeout',
    errorDetail: 'Failed to connect to CRM_System after 30 seconds. Check network connectivity.',
  },
  {
    id: 'run-004',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-17 02:15:00',
    endTime: '2026-05-17 02:32:10',
    duration: 1030000,
    retryCount: 1,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 4800,
    recordsFailed: 2,
  },
  {
    id: 'run-005',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-16 02:15:00',
    endTime: '2026-05-16 02:36:00',
    duration: 1260000,
    retryCount: 0,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 5100,
    recordsFailed: 0,
  },
  {
    id: 'run-006',
    jobId: 'job-001',
    status: 'FAILED',
    startTime: '2026-05-15 02:15:00',
    endTime: '2026-05-15 02:20:30',
    duration: 330000,
    retryCount: 2,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 1200,
    recordsFailed: 15,
    errorMessage: 'Memory allocation exceeded',
    errorDetail: 'Heap memory limit reached while processing batch #4.',
  },
  {
    id: 'run-007',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-14 02:15:00',
    endTime: '2026-05-14 02:33:40',
    duration: 1120000,
    retryCount: 0,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 4900,
    recordsFailed: 0,
  },
  {
    id: 'run-008',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-13 02:15:00',
    endTime: '2026-05-13 02:30:15',
    duration: 915000,
    retryCount: 0,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 4850,
    recordsFailed: 1,
  },
  {
    id: 'run-009',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-12 02:15:00',
    endTime: '2026-05-12 02:34:50',
    duration: 1190000,
    retryCount: 0,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 5020,
    recordsFailed: 0,
  },
  {
    id: 'run-010',
    jobId: 'job-001',
    status: 'FAILED',
    startTime: '2026-05-11 02:15:00',
    endTime: '2026-05-11 02:25:00',
    duration: 600000,
    retryCount: 3,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 2100,
    recordsFailed: 80,
    errorMessage: 'API Gateway Timeout',
    errorDetail: 'Upstream gateway 504 Gateway Timeout during sync batch.',
  },
  {
    id: 'run-011',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-10 02:15:00',
    endTime: '2026-05-10 02:31:00',
    duration: 960000,
    retryCount: 0,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 4980,
    recordsFailed: 0,
  },
  {
    id: 'run-012',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-09 02:15:00',
    endTime: '2026-05-09 02:35:10',
    duration: 1210000,
    retryCount: 1,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 5050,
    recordsFailed: 3,
  },
  {
    id: 'run-013',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-08 02:15:00',
    endTime: '2026-05-08 02:33:00',
    duration: 1080000,
    retryCount: 0,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 4900,
    recordsFailed: 0,
  },
  {
    id: 'run-014',
    jobId: 'job-001',
    status: 'SUCCESS',
    startTime: '2026-05-07 02:15:00',
    endTime: '2026-05-07 02:32:45',
    duration: 1065000,
    retryCount: 0,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 4870,
    recordsFailed: 0,
  },
  {
    id: 'run-015',
    jobId: 'job-001',
    status: 'RUNNING',
    startTime: '2026-05-20 20:15:00',
    duration: 180000,
    retryCount: 0,
    triggeredBy: 'scheduler',
    nodeIp: '192.168.10.15',
    triggerType: 'SCHEDULED',
    recordsProcessed: 2500,
    recordsFailed: 0,
  },
];

export const mockChangeHistoryData: IChangeHistoryItem[] = [
  {
    id: 'hist-001',
    timestamp: '2026-02-01T14:20:00Z',
    dateStr: '01/02/2026',
    fullTimeStr: '01/02/2026 14:20:00',
    updatedBy: 'manager_02',
    updatedByFullName: 'Trần Văn Quản Lý',
    action: 'Đổi lịch Cron',
    oldValue: 'cron: 0 0 12 * * *',
    newValue: 'cron: 0 0 1 * * *',
    ipAddress: '192.168.1.105',
    description: 'Điều chỉnh lịch chạy tự động hàng ngày từ 12:00 PM sang 01:00 AM theo yêu cầu quản trị hệ thống.',
    attachmentUrl: '#',
    attachmentName: 'bien_ban_phe_duyet_doi_lich.pdf',
  },
  {
    id: 'hist-002',
    timestamp: '2026-01-20T09:15:30Z',
    dateStr: '20/01/2026',
    fullTimeStr: '20/01/2026 09:15:30',
    updatedBy: 'admin_01',
    updatedByFullName: 'Nguyễn Văn Quản Trị',
    action: 'Cấu hình cảnh báo',
    oldValue: 'email: alert_old@cic.org.vn',
    newValue: 'email: admin@cic.org.vn, alert@cic.org.vn',
    ipAddress: '192.168.1.100',
    description: 'Bổ sung danh sách email người nhận thông báo tự động khi job gặp sự cố thất bại.',
  },
  {
    id: 'hist-003',
    timestamp: '2026-01-15T08:30:00Z',
    dateStr: '15/01/2026',
    fullTimeStr: '15/01/2026 08:30:00',
    updatedBy: 'admin_01',
    updatedByFullName: 'Nguyễn Văn Quản Trị',
    action: 'Tạo mới Job',
    oldValue: '',
    newValue: 'status: ACTIVE',
    ipAddress: '192.168.1.100',
    description: 'Khởi tạo cấu hình Job mới trên hệ thống CIC Core System.',
  },
];
