import type { IIndustryProduct } from './types';

export const INITIAL_PRODUCTS: IIndustryProduct[] = [
  {
    id: 'prod-001',
    code: 'SP-PTN-01',
    name: 'Báo cáo phân tích ngành Bán lẻ 2025',
    fiscalYear: 2025,
    industryCode: 'G47',
    industryName: 'Bán lẻ (trừ ô tô, mô tô, xe máy)',
    createdAt: '15/01/2026',
    createdBy: 'nguyenvana',
    creatorFullName: 'Nguyễn Văn An',
    status: 'APPROVED',
    approvedBy: 'admin',
    approverFullName: 'Quản trị hệ thống',
    approvedAt: '18/01/2026',
    approvalNote: 'Báo cáo đầy đủ các chỉ số tài chính ngành bán lẻ, số liệu đối chiếu khớp với kho chuẩn.',
    fileName: 'BC_PhanTich_Nganh_BanLe_2025.xlsx',
    fileSize: '4.8 MB',
    notes: 'Tổng hợp từ 1.250 doanh nghiệp ngành bán lẻ quy mô lớn và vừa.',
    history: [
      {
        id: 'hist-001-1',
        timestamp: '2026-01-18T14:35:20Z',
        dateStr: '18/01/2026',
        fullTimeStr: '18/01/2026 14:35:20',
        updatedBy: 'admin',
        updatedByFullName: 'Quản trị hệ thống',
        action: 'Phê duyệt',
        oldValue: 'Chờ duyệt',
        newValue: 'Đã duyệt',
        ipAddress: '192.168.1.10',
        description: 'Phê duyệt ban hành báo cáo phân tích ngành bán lẻ năm tài chính 2025',
      },
      {
        id: 'hist-001-2',
        timestamp: '2026-01-16T09:12:05Z',
        dateStr: '16/01/2026',
        fullTimeStr: '16/01/2026 09:12:05',
        updatedBy: 'nguyenvana',
        updatedByFullName: 'Nguyễn Văn An',
        action: 'Gửi duyệt',
        oldValue: 'Tạo mới',
        newValue: 'Chờ duyệt',
        ipAddress: '192.168.1.45',
        description: 'Gửi phê duyệt báo cáo kèm file kết quả phân tích chỉ số tài chính',
      },
      {
        id: 'hist-001-3',
        timestamp: '2026-01-15T08:30:00Z',
        dateStr: '15/01/2026',
        fullTimeStr: '15/01/2026 08:30:00',
        updatedBy: 'nguyenvana',
        updatedByFullName: 'Nguyễn Văn An',
        action: 'Tạo mới',
        oldValue: '-',
        newValue: 'Tạo mới',
        ipAddress: '192.168.1.45',
        description: 'Khởi tạo hồ sơ báo cáo phân tích ngành bán lẻ 2025',
      },
    ],
  },
  {
    id: 'prod-002',
    code: 'SP-PTN-02',
    name: 'Báo cáo trung bình ngành Xây dựng nhà 2025',
    fiscalYear: 2025,
    industryCode: 'F41',
    industryName: 'Xây dựng nhà các loại',
    createdAt: '20/01/2026',
    createdBy: 'tranthib',
    creatorFullName: 'Trần Thị Bình',
    status: 'PENDING',
    fileName: 'BC_TrungBinhNganh_XayDung_2025.xlsx',
    fileSize: '6.2 MB',
    notes: 'Bổ sung phân tích hệ số nợ trên vốn chủ sở hữu và khả năng thanh toán ngắn hạn.',
    history: [
      {
        id: 'hist-002-1',
        timestamp: '2026-01-21T10:25:40Z',
        dateStr: '21/01/2026',
        fullTimeStr: '21/01/2026 10:25:40',
        updatedBy: 'tranthib',
        updatedByFullName: 'Trần Thị Bình',
        action: 'Gửi duyệt',
        oldValue: 'Tạo mới',
        newValue: 'Chờ duyệt',
        ipAddress: '192.168.1.52',
        description: 'Gửi phê duyệt báo cáo trung bình ngành xây dựng',
      },
      {
        id: 'hist-002-2',
        timestamp: '2026-01-20T14:15:30Z',
        dateStr: '20/01/2026',
        fullTimeStr: '20/01/2026 14:15:30',
        updatedBy: 'tranthib',
        updatedByFullName: 'Trần Thị Bình',
        action: 'Tạo mới',
        oldValue: '-',
        newValue: 'Tạo mới',
        ipAddress: '192.168.1.52',
        description: 'Khởi tạo hồ sơ báo cáo',
      },
    ],
  },
  {
    id: 'prod-003',
    code: 'SP-PTN-03',
    name: 'Báo cáo phân tích ngành Chế biến thực phẩm 2024',
    fiscalYear: 2024,
    industryCode: 'C10',
    industryName: 'Chế biến thực phẩm',
    createdAt: '10/02/2025',
    createdBy: 'lethic',
    creatorFullName: 'Lê Thị Cúc',
    status: 'APPROVED',
    approvedBy: 'admin',
    approverFullName: 'Quản trị hệ thống',
    approvedAt: '12/02/2025',
    approvalNote: 'Đạt yêu cầu chất lượng dữ liệu ngành chế biến thực phẩm.',
    fileName: 'BC_PhanTich_CheBienThucPham_2024.docx',
    fileSize: '3.5 MB',
    notes: 'Báo cáo phục vụ chấm điểm tín dụng và đánh giá rủi ro ngành.',
    history: [
      {
        id: 'hist-003-1',
        timestamp: '2025-02-12T16:00:15Z',
        dateStr: '12/02/2025',
        fullTimeStr: '12/02/2025 16:00:15',
        updatedBy: 'admin',
        updatedByFullName: 'Quản trị hệ thống',
        action: 'Phê duyệt',
        oldValue: 'Chờ duyệt',
        newValue: 'Đã duyệt',
        ipAddress: '192.168.1.10',
        description: 'Duyệt ban hành số liệu chính thức',
      },
      {
        id: 'hist-003-2',
        timestamp: '2025-02-10T09:00:00Z',
        dateStr: '10/02/2025',
        fullTimeStr: '10/02/2025 09:00:00',
        updatedBy: 'lethic',
        updatedByFullName: 'Lê Thị Cúc',
        action: 'Tạo mới',
        oldValue: '-',
        newValue: 'Tạo mới',
        ipAddress: '192.168.1.58',
        description: 'Khởi tạo báo cáo ngành chế biến thực phẩm 2024',
      },
    ],
  },
  {
    id: 'prod-004',
    code: 'SP-PTN-04',
    name: 'Báo cáo trung bình ngành Dịch vụ tài chính 2025',
    fiscalYear: 2025,
    industryCode: 'K64',
    industryName: 'Hoạt động dịch vụ tài chính',
    createdAt: '01/02/2026',
    createdBy: 'phamvand',
    creatorFullName: 'Phạm Văn Dũng',
    status: 'REJECTED',
    approvedBy: 'admin',
    approverFullName: 'Quản trị hệ thống',
    approvedAt: '03/02/2026',
    rejectReason: 'Dữ liệu chỉ tiêu ROE và NIM chưa đồng bộ với kỳ báo cáo quý IV/2025. Cần kiểm tra lại tệp nguồn.',
    fileName: 'BC_TrungBinhNganh_TaiChinh_2025_draft.xlsx',
    fileSize: '5.1 MB',
    notes: 'Đang chuẩn bị bổ sung dữ liệu các công ty tài chính tiêu dùng.',
    history: [
      {
        id: 'hist-004-1',
        timestamp: '2026-02-03T11:45:00Z',
        dateStr: '03/02/2026',
        fullTimeStr: '03/02/2026 11:45:00',
        updatedBy: 'admin',
        updatedByFullName: 'Quản trị hệ thống',
        action: 'Từ chối duyệt',
        oldValue: 'Chờ duyệt',
        newValue: 'Từ chối duyệt',
        ipAddress: '192.168.1.10',
        description: 'Từ chối duyệt: Dữ liệu chỉ tiêu ROE và NIM chưa đồng bộ kỳ báo cáo',
      },
      {
        id: 'hist-004-2',
        timestamp: '2026-02-02T09:30:10Z',
        dateStr: '02/02/2026',
        fullTimeStr: '02/02/2026 09:30:10',
        updatedBy: 'phamvand',
        updatedByFullName: 'Phạm Văn Dũng',
        action: 'Gửi duyệt',
        oldValue: 'Tạo mới',
        newValue: 'Chờ duyệt',
        ipAddress: '192.168.1.66',
        description: 'Trình lãnh đạo phê duyệt',
      },
    ],
  },
  {
    id: 'prod-005',
    code: 'SP-PTN-05',
    name: 'Báo cáo phân tích Logistics và kho bãi 2025',
    fiscalYear: 2025,
    industryCode: 'H52',
    industryName: 'Kho bãi và các hoạt động hỗ trợ vận tải',
    createdAt: '05/02/2026',
    createdBy: 'nguyenvana',
    creatorFullName: 'Nguyễn Văn An',
    status: 'DRAFT',
    fileName: 'BC_Logistics_KhoBai_2025_SoBo.xlsx',
    fileSize: '2.9 MB',
    notes: 'Bản thảo ban đầu, đang rà soát dữ liệu định kỳ cùng kỳ.',
    history: [
      {
        id: 'hist-005-1',
        timestamp: '2026-02-05T15:10:20Z',
        dateStr: '05/02/2026',
        fullTimeStr: '05/02/2026 15:10:20',
        updatedBy: 'nguyenvana',
        updatedByFullName: 'Nguyễn Văn An',
        action: 'Tạo mới',
        oldValue: '-',
        newValue: 'Tạo mới',
        ipAddress: '192.168.1.45',
        description: 'Tạo dự thảo báo cáo phân tích ngành logistics',
      },
    ],
  },
  {
    id: 'prod-006',
    code: 'SP-PTN-06',
    name: 'Báo cáo trung bình ngành Nông nghiệp công nghệ cao 2025',
    fiscalYear: 2025,
    industryCode: 'A01',
    industryName: 'Nông nghiệp và hoạt động dịch vụ liên quan',
    createdAt: '12/01/2026',
    createdBy: 'hoangthie',
    creatorFullName: 'Hoàng Thị Em',
    status: 'RECALLED',
    approvedBy: 'admin',
    approverFullName: 'Quản trị hệ thống',
    approvedAt: '15/01/2026',
    recallReason: 'Phát hiện sai lệch mã ngành của 12 doanh nghiệp chế biến nông sản trong tập mẫu; thu hồi để cập nhật lại.',
    fileName: 'BC_TB_Nganh_NongNghiep_2025.xlsx',
    fileSize: '4.2 MB',
    notes: 'Thu hồi theo đề nghị của phòng Nghiệp vụ phân tích sản phẩm.',
    history: [
      {
        id: 'hist-006-1',
        timestamp: '2026-01-19T09:15:30Z',
        dateStr: '19/01/2026',
        fullTimeStr: '19/01/2026 09:15:30',
        updatedBy: 'hoangthie',
        updatedByFullName: 'Hoàng Thị Em',
        action: 'Thu hồi',
        oldValue: 'Đã duyệt',
        newValue: 'Thu hồi',
        ipAddress: '192.168.1.72',
        description: 'Thu hồi do phát hiện sai lệch 12 doanh nghiệp mẫu',
      },
      {
        id: 'hist-006-2',
        timestamp: '2026-01-15T16:30:00Z',
        dateStr: '15/01/2026',
        fullTimeStr: '15/01/2026 16:30:00',
        updatedBy: 'admin',
        updatedByFullName: 'Quản trị hệ thống',
        action: 'Phê duyệt',
        oldValue: 'Chờ duyệt',
        newValue: 'Đã duyệt',
        ipAddress: '192.168.1.10',
        description: 'Phê duyệt hồ sơ',
      },
    ],
  },
  {
    id: 'prod-007',
    code: 'SP-PTN-07',
    name: 'Báo cáo phân tích ngành Khách sạn - Dịch vụ lưu trú 2025',
    fiscalYear: 2025,
    industryCode: 'I55',
    industryName: 'Dịch vụ lưu trú',
    createdAt: '08/02/2026',
    createdBy: 'tranthib',
    creatorFullName: 'Trần Thị Bình',
    status: 'PENDING',
    fileName: 'BC_LuuTru_KhachSan_2025.xlsx',
    fileSize: '3.8 MB',
    notes: 'Đánh giá tỷ lệ lấp đầy phòng và hệ số đòn bẩy tài chính.',
    history: [
      {
        id: 'hist-007-1',
        timestamp: '2026-02-09T08:45:00Z',
        dateStr: '09/02/2026',
        fullTimeStr: '09/02/2026 08:45:00',
        updatedBy: 'tranthib',
        updatedByFullName: 'Trần Thị Bình',
        action: 'Gửi duyệt',
        oldValue: 'Tạo mới',
        newValue: 'Chờ duyệt',
        ipAddress: '192.168.1.52',
        description: 'Gửi duyệt báo cáo ngành lưu trú',
      },
    ],
  },
  {
    id: 'prod-008',
    code: 'SP-PTN-08',
    name: 'Báo cáo phân tích ngành Công nghệ thông tin 2025',
    fiscalYear: 2025,
    industryCode: 'J62',
    industryName: 'Lập trình máy vi tính, tư vấn và quản trị',
    createdAt: '14/01/2026',
    createdBy: 'phamvand',
    creatorFullName: 'Phạm Văn Dũng',
    status: 'APPROVED',
    approvedBy: 'admin',
    approverFullName: 'Quản trị hệ thống',
    approvedAt: '17/01/2026',
    approvalNote: 'Báo cáo chi tiết, dữ liệu tăng trưởng doanh thu và lợi nhuận hợp lệ.',
    fileName: 'BC_Nganh_CNTT_PhanMem_2025.xlsx',
    fileSize: '5.6 MB',
    notes: 'Tập trung vào các doanh nghiệp phần mềm và giải pháp chuyển đổi số.',
    history: [
      {
        id: 'hist-008-1',
        timestamp: '2026-01-17T15:20:00Z',
        dateStr: '17/01/2026',
        fullTimeStr: '17/01/2026 15:20:00',
        updatedBy: 'admin',
        updatedByFullName: 'Quản trị hệ thống',
        action: 'Phê duyệt',
        oldValue: 'Chờ duyệt',
        newValue: 'Đã duyệt',
        ipAddress: '192.168.1.10',
        description: 'Phê duyệt chính thức',
      },
    ],
  },
];
