import type { IProduct } from './productTypes';

export const MOCK_PRODUCTS: IProduct[] = [
  {
    id: '1',
    code: 'K11',
    name: 'Báo cáo tín dụng cá nhân cơ bản',
    productType: 'TRADITIONAL',
    productGroup: 'CREDIT_RELATION',
    subjectType: ['INDIVIDUAL'],
    language: ['VN'],
    version: '1.0',
    status: 'ACTIVE',
    effectiveDate: '01/06/2026',
    expiredDate: '31/12/2030',
    inquiryChannels: ['WEB_FORM', 'API'],
    inquiryModes: ['SINGLE_ITEM'],
    inputFormats: ['FORM', 'JSON'],
    maxRecordsWebUi: 1,
    maxRecordsFileUpload: 200,
    maxRecordsApi: 1000,
    fulfillmentModes: ['IMMEDIATE'],
    dataMode: 'ON_DEMAND',
    allowPartialResponse: true,
    allowRetry: true,
    allowReprocess: true,
    manualReviewRequired: 'conditional',
    pendingReasons: ['DATA_ADJUSTMENT', 'MANUAL_REVIEW'],
    outputTypes: ['REPORT'],
    outputFormats: ['PDF'],
    configurableFields: false,
    customAliasFields: false,
    templateBased: true,
    versionedTemplate: true,
    digitalSignatureRequired: 'optional',
    encryptionRequired: 'conditional',
    deliveryChannels: ['WEB_DOWNLOAD'],
    partialDeliverySupported: false,
    deliveryAckRequired: true,
    permissionRequired: true,
    consentRequired: 'conditional',
    auditRequired: true,
    pricingRequired: true,
    slaRequired: true,
  },
  {
    id: '2',
    code: 'K12',
    name: 'Báo cáo tín dụng cá nhân nâng cao',
    productType: 'TRADITIONAL',
    productGroup: 'CREDIT_RELATION',
    subjectType: ['INDIVIDUAL'],
    language: ['VN', 'EN'],
    version: '2.0',
    status: 'ACTIVE',
    effectiveDate: '01/06/2026',
    expiredDate: '31/12/2030',
    inquiryChannels: ['WEB_FORM', 'FILE_UPLOAD', 'API'],
    inquiryModes: ['SINGLE_ITEM', 'MULTI_ITEMS'],
    inputFormats: ['FORM', 'EXCEL', 'JSON'],
    maxRecordsWebUi: 1,
    maxRecordsFileUpload: 200,
    maxRecordsApi: 1000,
    fulfillmentModes: ['IMMEDIATE', 'ASYNC'],
    dataMode: 'ON_DEMAND',
    allowPartialResponse: true,
    allowRetry: true,
    allowReprocess: true,
    manualReviewRequired: 'conditional',
    pendingReasons: ['DATA_ADJUSTMENT', 'INVALID_IDENTIFIER', 'MANUAL_REVIEW'],
    outputTypes: ['REPORT', 'DATA_FILE'],
    outputFormats: ['PDF', 'EXCEL'],
    configurableFields: true,
    customAliasFields: true,
    templateBased: true,
    versionedTemplate: true,
    digitalSignatureRequired: 'required',
    encryptionRequired: 'conditional',
    deliveryChannels: ['WEB_DOWNLOAD', 'NOTIFICATION'],
    partialDeliverySupported: true,
    deliveryAckRequired: true,
    permissionRequired: true,
    consentRequired: 'required',
    auditRequired: true,
    pricingRequired: true,
    slaRequired: true,
  },
  {
    id: '3',
    code: 'K21',
    name: 'Báo cáo tín dụng doanh nghiệp cơ bản',
    productType: 'TRADITIONAL',
    productGroup: 'ENTERPRISE_REPORT',
    subjectType: ['ORGANIZATION'],
    language: ['VN'],
    version: '1.0',
    status: 'ACTIVE',
    effectiveDate: '01/06/2026',
    expiredDate: '31/12/2030',
    inquiryChannels: ['WEB_FORM', 'API'],
    inquiryModes: ['SINGLE_ITEM'],
    inputFormats: ['FORM', 'JSON'],
    maxRecordsWebUi: 1,
    maxRecordsFileUpload: 200,
    maxRecordsApi: 1000,
    fulfillmentModes: ['IMMEDIATE'],
    dataMode: 'ON_DEMAND',
    allowPartialResponse: false,
    allowRetry: true,
    allowReprocess: false,
    manualReviewRequired: 'never',
    pendingReasons: [],
    outputTypes: ['REPORT'],
    outputFormats: ['PDF'],
    configurableFields: false,
    customAliasFields: false,
    templateBased: true,
    versionedTemplate: true,
    digitalSignatureRequired: 'optional',
    encryptionRequired: 'none',
    deliveryChannels: ['WEB_DOWNLOAD'],
    partialDeliverySupported: false,
    deliveryAckRequired: false,
    permissionRequired: true,
    consentRequired: 'none',
    auditRequired: true,
    pricingRequired: true,
    slaRequired: true,
  },
  {
    id: '4',
    code: 'K31',
    name: 'Chấm điểm tín dụng cá nhân',
    productType: 'ON_DEMAND',
    productGroup: 'SCORING_RATING',
    subjectType: ['INDIVIDUAL'],
    language: ['VN'],
    version: '3.1',
    status: 'ACTIVE',
    effectiveDate: '01/01/2026',
    expiredDate: '31/12/2028',
    inquiryChannels: ['API'],
    inquiryModes: ['SINGLE_ITEM', 'BATCH'],
    inputFormats: ['JSON', 'XML'],
    maxRecordsWebUi: 1,
    maxRecordsFileUpload: 200,
    maxRecordsApi: 1000,
    fulfillmentModes: ['IMMEDIATE', 'ASYNC'],
    dataMode: 'ON_DEMAND',
    allowPartialResponse: false,
    allowRetry: true,
    allowReprocess: false,
    manualReviewRequired: 'never',
    pendingReasons: ['DATA_NOT_READY'],
    outputTypes: ['API_RESPONSE'],
    outputFormats: ['JSON'],
    configurableFields: true,
    customAliasFields: true,
    templateBased: false,
    versionedTemplate: false,
    digitalSignatureRequired: 'none',
    encryptionRequired: 'required',
    deliveryChannels: ['API_RESPONSE', 'API_CALLBACK'],
    partialDeliverySupported: false,
    deliveryAckRequired: false,
    permissionRequired: true,
    consentRequired: 'none',
    auditRequired: true,
    pricingRequired: true,
    slaRequired: true,
  },
  {
    id: '5',
    code: 'K41',
    name: 'Báo cáo định kỳ tháng — Khách hàng cá nhân',
    productType: 'PERIODIC',
    productGroup: 'CREDIT_RELATION',
    subjectType: ['INDIVIDUAL'],
    language: ['VN'],
    version: '1.5',
    status: 'ACTIVE',
    effectiveDate: '01/01/2026',
    expiredDate: '31/12/2030',
    inquiryChannels: ['SCHEDULER'],
    inquiryModes: ['BATCH'],
    inputFormats: ['CSV', 'EXCEL'],
    maxRecordsWebUi: 1,
    maxRecordsFileUpload: 200,
    maxRecordsApi: 1000,
    fulfillmentModes: ['PERIODIC_PRECOMPUTED', 'BATCH'],
    dataMode: 'PRECOMPUTED',
    allowPartialResponse: true,
    allowRetry: true,
    allowReprocess: true,
    manualReviewRequired: 'conditional',
    pendingReasons: ['DATA_NOT_READY', 'DATA_ADJUSTMENT'],
    outputTypes: ['REPORT', 'DATA_FILE'],
    outputFormats: ['PDF', 'EXCEL', 'ZIP'],
    configurableFields: true,
    customAliasFields: false,
    templateBased: true,
    versionedTemplate: true,
    digitalSignatureRequired: 'required',
    encryptionRequired: 'conditional',
    deliveryChannels: ['WEB_DOWNLOAD', 'NOTIFICATION'],
    partialDeliverySupported: true,
    deliveryAckRequired: true,
    permissionRequired: true,
    consentRequired: 'required',
    auditRequired: true,
    pricingRequired: true,
    slaRequired: true,
  },
  {
    id: '6',
    code: 'K51',
    name: 'Báo cáo cảnh báo rủi ro tín dụng',
    productType: 'ANALYSIS_ARTICLE',
    productGroup: 'ALERT_MONTHLY',
    subjectType: ['INDIVIDUAL', 'ORGANIZATION'],
    language: ['VN'],
    version: '1.0',
    status: 'INACTIVE',
    effectiveDate: '01/03/2026',
    expiredDate: '31/12/2027',
    inquiryChannels: ['INTERNAL_JOB'],
    inquiryModes: ['BATCH'],
    inputFormats: ['JSON'],
    maxRecordsWebUi: 1,
    maxRecordsFileUpload: 200,
    maxRecordsApi: 1000,
    fulfillmentModes: ['ASYNC', 'BATCH'],
    dataMode: 'ON_DEMAND',
    allowPartialResponse: true,
    allowRetry: false,
    allowReprocess: false,
    manualReviewRequired: 'always',
    pendingReasons: ['MANUAL_REVIEW'],
    outputTypes: ['REPORT'],
    outputFormats: ['PDF'],
    configurableFields: false,
    customAliasFields: false,
    templateBased: true,
    versionedTemplate: false,
    digitalSignatureRequired: 'none',
    encryptionRequired: 'none',
    deliveryChannels: ['NOTIFICATION'],
    partialDeliverySupported: false,
    deliveryAckRequired: false,
    permissionRequired: true,
    consentRequired: 'none',
    auditRequired: true,
    pricingRequired: false,
    slaRequired: false,
  },
  {
    id: '7',
    code: 'K22',
    name: 'Báo cáo tín dụng tập đoàn toàn diện',
    productType: 'CUSTOM',
    productGroup: 'ENTERPRISE_REPORT',
    subjectType: ['GROUP_CORPORATION'],
    language: ['VN', 'EN'],
    version: '1.0',
    status: 'INACTIVE',
    effectiveDate: '01/07/2026',
    expiredDate: '31/12/2029',
    inquiryChannels: ['API', 'INTERNAL_JOB'],
    inquiryModes: ['SINGLE_ITEM'],
    inputFormats: ['JSON', 'XML'],
    maxRecordsWebUi: 1,
    maxRecordsFileUpload: 200,
    maxRecordsApi: 1000,
    fulfillmentModes: ['ASYNC'],
    dataMode: 'ON_DEMAND',
    allowPartialResponse: true,
    allowRetry: true,
    allowReprocess: true,
    manualReviewRequired: 'conditional',
    pendingReasons: ['DATA_ADJUSTMENT', 'INVALID_IDENTIFIER'],
    outputTypes: ['REPORT', 'DATA_FILE', 'API_RESPONSE'],
    outputFormats: ['PDF', 'EXCEL', 'JSON', 'XML'],
    configurableFields: true,
    customAliasFields: true,
    templateBased: true,
    versionedTemplate: true,
    digitalSignatureRequired: 'required',
    encryptionRequired: 'required',
    deliveryChannels: ['WEB_DOWNLOAD', 'API_RESPONSE', 'API_CALLBACK'],
    partialDeliverySupported: true,
    deliveryAckRequired: true,
    permissionRequired: true,
    consentRequired: 'required',
    auditRequired: true,
    pricingRequired: true,
    slaRequired: true,
  },
  {
    id: '8',
    code: 'K61',
    name: 'Báo cáo tín dụng khách hàng vay',
    productType: 'ON_DEMAND',
    productGroup: 'BORROWER',
    subjectType: ['INDIVIDUAL', 'ORGANIZATION'],
    language: ['VN'],
    version: '2.0',
    status: 'ACTIVE',
    effectiveDate: '01/01/2026',
    expiredDate: '31/12/2030',
    inquiryChannels: ['WEB_FORM', 'API'],
    inquiryModes: ['SINGLE_ITEM', 'MULTI_ITEMS'],
    inputFormats: ['FORM', 'JSON'],
    maxRecordsWebUi: 1,
    maxRecordsFileUpload: 200,
    maxRecordsApi: 1000,
    fulfillmentModes: ['IMMEDIATE'],
    dataMode: 'ON_DEMAND',
    allowPartialResponse: false,
    allowRetry: true,
    allowReprocess: false,
    manualReviewRequired: 'never',
    pendingReasons: [],
    outputTypes: ['REPORT'],
    outputFormats: ['PDF'],
    configurableFields: false,
    customAliasFields: false,
    templateBased: true,
    versionedTemplate: true,
    digitalSignatureRequired: 'optional',
    encryptionRequired: 'conditional',
    deliveryChannels: ['WEB_DOWNLOAD'],
    partialDeliverySupported: false,
    deliveryAckRequired: true,
    permissionRequired: true,
    consentRequired: 'conditional',
    auditRequired: true,
    pricingRequired: true,
    slaRequired: true,
  },
];
